---
title: A shapefile of Wisconsin November 2018 reporting units
author: John D. Johnson
date: '2018-12-10'
slug: a-shapefile-of-wisconsin-november-2018-reporting-units
categories:
  - Wisconsin
  - Elections
tags: []
Description: ''
Tags: []
Categories: []
DisableComments: no
---


As Wisconsin data nerds know, election results aren't actually reported by individual wards. In less-populated areas, local elections officials are allowed to protect voters' anonymity by combing multiple wards into larger "reporting units." These reporting units are still required to lie entirely within the smallest relevant political boundary.

While understandable from a voter privacy perspective, this practice can be frustrating for data analysis. Reporting units change from election to election and no state agency makes a shapefile of them (to my knowledge). The excellent **[Legislative Technology Services Bureau](https://data-ltsb.opendata.arcgis.com/)** usually makes a disaggregated ward-level dataset available at some point after each general election. Still, this data is disaggrated and thus contains some inevitable uncertainty.

To solve this problem, I've created a shapefile with polygons for each reporting unit. 

##  Download
**[You can download the shapefile as a zipped archive here.](https://drive.google.com/open?id=1hGtQ9bWghpJMbsHogbAPb-2ANQ1LsSDe)**

##  Variables
The file also contains attribute fields for election data including congressional, state assembly, and state senate district numbers.

The variables have descriptive names, like "sen_dem" for Democratic votes for senator. Here are the meanings of each prefix:

* gov = Governor
* sen = Senator
* con = House of Representatives
* wsa = Wisconsin State Assembly
* wss = Wisconsin State Senate
* wst = Wisconsin State Treasurer
* sos = Secretary of State
* ag  = Attorney General

##  Data notes and disclaimer
I've made every effort to ensure the accuracy of this data, but errors may persist nonetheless.

The fall 2018 ward boundaries file I used to create the reporting units shapefile was generated by the LTSB in the months before the election. A few municipal boundary changes occured between the finalization of the LTSB shapefile and the election itself so there is not perfect alignment between the wards as reported in the election results and the ward shapefile. Here are how I've handled those cases.

* Election results for Kenosha City ward 101 are recoded to Town of Somers Ward 2, which was its previous location. Three people voted in this race.
* Likewise, results for City of Waukesha Ward 50 are recoded to Town of Waukesha Ward 1, where they were previously situated. This also affected just 3 votes.

There were also a couple instances where it appears a municipality was named one thing in the ward shapefile and another in the reporting units election results. These seems to be due to incorporations or mergers between municipalities.

* The polygons for Town of Williamstown Wards 1-3 were combined with Village of Kekoskee Wards 1-3.
* The polygons for Village of Brokaw Ward 1 were assigned to the Village of Maine Reporting Wards 1-4.

In perhaps a dozen instances, some of the wards mentioned in the reporting unit description were present in the ward shapefile, while at least one other was not. In these cases, the votes for the entire reporting unit were assigned to the polygon merged out of the known wards.

Finally, I could ascertain no likely match for 7 reporting units; however, all of them recorded 0 votes in 2018. Perhaps they are unoccupied land or nonexistent administrative vestiges.
