---
title: Wisconsin elections dataset
author: John D. Johnson
date: '2019-06-14'
slug: wisconsin-elections-dataset
categories:
  - Wisconsin
  - Elections
tags: []
Description: ''
Tags: []
Categories: []
DisableComments: no
---

[Download an MCD-level dataset of every Wisconsin election for president, governor, and senate from 2000 to 2018 here.](https://www.dropbox.com/s/jo5e9pukptpf1u2/WI_GovPresSen_2000to2018.csv?dl=0)

This dataset contains the following fields:

* CNTY_NAME - e.g. "Adams"
* MCD_NAME - e.g. "City Of Adams"
* CNTY_FIPS - e.g. "55001"
* MCD_FIPS - e.g. "5500100275"
* year
* race - one of "PRE", "GOV", or "SEN"
* CTV - one of "C", "T", or "V" indicating "city", "town", or "village"
* REP - votes cast for the Republican
* DEM - votes cast for the Democrat
* GRN - votes cast for the Green candidate
* LIB - votes cast for the Libertarian candidate
* OTH - votes cast for any other candidates
* TOT - total votes cast

All data was built using official returns from the website of the Wisconsin Elections Commission. The MCD_FIPS field should match the official Census Bureau designation for that year. Use this field to merge Census data of the appropriate vintage. This dataset was built with the assistance of Ricardo Morales Vivero. Please send all questions and comments to john.d.johnson@marquette.edu.