---
title: Books I read in 2019
author: John D. Johnson
date: '2020-01-02'
slug: books-i-read-in-2019
categories:
  - Personal
tags: []
Description: ''
Tags: []
Categories: []
DisableComments: no
---


Here are the books I read in 2019. Some years I read a lot of fiction, but for whatever reason this was a good year for nonfiction. They are presented in no particular order.

***Days of Rage: America's Radical Underground, the FBI, and the Forgotten Age of Revolutionary Violence*** by Bryan Burrough (2015)

Left-wing political groups detonated several thousand bombs across the United States during the early 1970s. Burroughs lays out one of the first lengthy historical accounts of this often forgotten period. A longtime journalist, he convinced many participants to go on the record for the first time. Most of the book meticulous reconstructs specific events, following the evolution of several selected revolutionary groups. The Weathermen, Symbionese Liberation Army, and FALN, among others. Burroughs spends less time contextualizing the political climate of the era, though he does effectively illustrate its foreignness. After a bomb went off in a New York cinema, the uninjured crowd booed as police tried to stop the movie and evacuate the building. Despite its strangeness, the era has echoes into the present. One politician targeted by Bay Area radicals was a young county supervisor named Diane Feinstein. They blew up a package on her windowsill. I thought about that this year when I saw images of her office being occupied by sit-in demonstrators.

***The Norse Atlantic Saga: Being the Norse Voyages of Discovery and Settlement to Iceland, Greenland, and North America*** by Gwyn Jones (1986)

This is both a history book and a collection of primary sources. The author includes the Viking Sagas recounting their adventures in the Faroe Islands, Iceland, Greenland, and Vinland, but the meat of the book is a lengthy and fascinating discussion of the historical events they describe—drawing primarily on written and archaeological records. Of particular interest to me is the story of the Greenland colony, which lasted for 400 years before petering out into oblivion about one lifetime before Columbus’ voyage. Greenland was uninhabited when the Vikings arrived (the Dorset culture had left behind stone dwellings but little indication why they left), but migrants from North America (the Thule culture) resettled it some centuries later. As the Little Ice Age set in, the Viking descendants’ traditional sea route to Iceland was choked with ice and their farms failed. The Thule people were hunter-gatherers better equipped to handle a changing climate.

***Hunting LeRoux: The Inside Story of the DEA Takedown of a Criminal Genius and His Empire*** by Elaine Shannon (2019)

Paul Leroux is like Elon Musk’s crappy evil cousin. He was born in Rhodesia during the waning years of the apartheid government. Eventually he wound up in Europe were he became an impressively skilled coder. Always looking for more money, he wound up in the Philippines where he made a fortune selling mail-order drugs to US customers. Eventually his aspirations extended to building an international criminal empire of drug and weapons dealing up to and including the development and manufacturing of his own products. In the author’s telling, his technological sophistication and reliance on the internet set him apart from traditional underworld operatives. Despite his eventual capture by the DEA, she characterizes him as representing a frightening new world of transnational digitally-enabled crime. This part of the book seemed oversold to me. I think it would have made a better long-from magazine article than a book.

******Essays******

Some of my best reading this year came in the form of essays. Essays of widely varying quality are unavoidable on the internet, but in addition to those, I read three essay collections. The hardest challenge in thinking clearly, is (for me at least) avoiding sycophancy on the one hand and contrarianism on the other. It’s easiest to just let the conventional wisdom of our increasingly thick social bubbles do our “thinking” for us. Many essayist do this, especially online. The three essay collections I read don’t, but one falls into, at times, the trap of contrarianism (also pervasive online). Contrarianism masquerades as freethinking, but reflexive disagreement with conventional wisdom is still inevitability in thrall to that same status quo. 

***Trick Mirror: Reflections on Self-Delusion*** by Jia Tolentino (2019)

Jia Tolentino seems like the kind of person for whom cognitive dissonance is intolerably itchy. In my favorite essay, “Always be Optimizing” she reckons with (among other things) the insidious persistence of the beauty ideal in contemporary body-positive feminism. In “We Come from Old Virginia” she writes the piece Rolling Stone should have published about UVA (her alma mater). The riskiest essay in this collection is “The Cult of the Difficult Woman,” which I recommend reading but is too nuanced to summarize here. Tolentino’s essays are compelling even when you don’t agree with them because her curiosity is honest and her self-doubt is neither disguised or hidden behind. She introduces the collection like this, “I’ve been telling myself that I wrote this book because I was confused after the election, because confusion sits at odds with my temperament, because writing is my only strategy for making this conflict go away. I’m convinced by this even as I can see its photonegative: I wrote this book because I am always confused, because I can never be sure of anything, and because I am drawn to any mechanism that directs me away from that truth. Writing is either a way to shed my self-delusions or a way to develop them.”

***Feel Free*** by Zadie Smith (2018)

More than 30 essays make up this collection. They are grouped by themes. Most of my favorites deal with politics broadly speaking—class, race, Brexit, gentrification. Smith simply calls this section “In the World.” Subjects that have been written half to death (or more), Smith brings the sincerity and perceptiveness of her best contemporaries with the self-serving pieties and ideological blinkers that characterize so much socio-political analysis. The bulk of the book, though is about art of all kinds--”in the audience,” “in the gallery,” or “on the bookshelf.” Some of these fascinated me. “Killing Orson Welles at Midnight” describes Christian Marclay’s 24-hour film The Clock. It consists entirely of little clips of other movies stitched together. Each clip is unified by showing the current time, sometimes intentionally, sometimes incidentally. Other essays simply remind me how far away the world of artists often is from my own.

***The Souls of Yellow Folk*** by Wesley Yang (2018)

Shorter and angrier than the other two, Wesley Yang’s facetiously titled collection sometimes lapses into contrarianism, but at his best Yang wields empathy like a knife. The crux of his worldview, as I understand it, is that Asian men in America occupy a space outside the hierarchies of identity that characterize so much of American life, sort of like the priest’s sons of late tsarist Russia. In this way, Yang both resents the implication that he speaks for a broader group and also acknowledges that, inevitably, he does in some sense. The first essay was, to me, the most memorable. In “The Face of Seung-Hui Oo” Yang accomplishes the rare feat of usefully plumbing his own self-loathing. “Jasper once told me that I was ‘essentially unlovable.’ I’ve always held this observation close to my heart, turning to it often. It’s true of some people—that there’s no reason anyone should love or care about them, because they aren’t appealing on the outside, and that once you dig into the real person beneath the shell (if, for some obscure if not actively perverse reason, you bother), you’ll find the real inner ugliness.” Yang writes this in the context of America’s epidemic of young male mass killers. It’s not a topic I recommend delving. But if you want to, read this essay.

***Nature's Mutiny: How the Little Ice Age of the Long Seventeenth Century Transformed the West and Shaped the Present*** by Phillipp Blom (2019)

The Little Ice Age did a lot more than choke off medieval Europe’s west-most outpost in Greenland, or so argues the German journalist Philipp Blom. In this roving intellectual popular history, he argues that the dramatic century plus long cold snap caused the urbanization that made capitalism possible. Moving from politics and economics, he surveys enduring changes in philosophy and art. I learned a lot (and had fun doing it) even if he didn’t always defend his thesis of the climate’s influence with the rigor of a professional historian.

***Krakatoa: the Day the World Exploded: August 27, 1883*** by Simon Winchester (2003)

You might not have heard of Krakatoa’s volcanic eruption, but if you lived in the 1880s you almost certainly would’ve noticed it. It was possibly the loudest sound in human history. People heard it almost 2,000 miles away. Bodies floated all the way to Africa. Waves reached Europe. The story of the volcano alone would justify a book, but Simon Winchester develops it into a sprawling account of too many things to list: the birth of early international news services, Dutch colonialism, early Islamism, and the discovery of plate tectonics to name just a few. Frankly, I found Winchester’s good-old-boy colonial era attitudes nearly insufferable, but the book is so full of fascinating information I couldn’t put it down.

***American Cosmic: UFOs, Religion, Technology*** by D.W. Pasulka (2019)

This is the strangest book I read all year. I think it’s an academic religious studies book about how UFOlogy has morphed into a religion with incomprehensibly advanced technology occupying a sort of sacramental role. This is certainly one half of what the author, a professor at UNC, is trying to do. At the same time, she is also telling a story of her own experiences with a shadowy group of people studying UFO evidence outside of the public eye. By the end of the book she is quite convinced aliens are real and visiting Earth, even as she insists that the reality of UFOs is irrelevant to the status of UFOlogy as a religion. I found it dissatisfying, but I still kept thinking about what I’d read for weeks after.

***The Undoing Project: A Friendship That Changed Our Minds*** by Michael Lewis (2016)

If you like Shankar Vedantam’s NPR show Hidden Brain, you’ll probably like this book. It’s about two Israeli psychologists, Amos Tversky and Daniel Khaneman who, together, discovered much of what we know today about systematic cognitive bias and other quirks of seemingly irrational human decisionmaking. Michael Lewis doesn’t just write about these mental phenomena though. At its heart, the book is about the collaborative friendship, almost an intellectual romance between two very different brilliant minds, that produced them. 

***The Big Short*** by Michael Lewis (2010)

I stayed up late reading this book like it was a thriller. Would that I could write about polling like Lewis writes about mortgage finances. If you want to understand the financial crisis, this is even better than the movie.

***Tinker, Tailor, Soldier, Spy*** by John le Carré (1974)

In John le Carré’s telling, a spy’s career is defined by long periods of time where nothing happens but their paranoia inexorably grows. I’m willing to believe him, since he actually was a spy earlier in his career. Very little at all happens in this wonderful book, but it carried me along more than just about any thriller I’ve read.

***The Geography of Southwestern Wisconsin*** by W.O. Blanchard (1924)

About a hundred years ago, the State of Wisconsin published some official geographical (in the broad sense) surveys of various regions around the state. This one covers the unglaciated part of the state now known as the Driftless Area. If you’ve ever wanted to see a hand-drawn dot map of hog densities in 1910, just let me know.

***London: The Information Capital : 100 Maps and Graphics that Will Change how You View the City*** by Cheshire and Uberti (2014)

In another bit of work-related reading, I picked up this book seeking data visualization inspiration. People who care about London will also find it interesting. The maps are beautiful (and largely reproducible with R), but I was also left envious of the visually pleasing irregular census boundaries used in England. There’s only so much you can do with our relentlessly rectangular American geographies.

***The Pleasures of Reading in an Age of Distraction*** by Alan Jacobs (2011)

Alan Jacobs is a critic of digital technology (or at least how we interact with it) and a proponent of reading. This makes him sound like a dime-a-dozen cranky old man, but he is saved from this fate by his pervasive optimism and non-judgmental outlook. His best two pieces of advice in this book are (1) read a lot of whatever you want, and (2) when you want something new to read, avoid the books that imitate the authors you like. Instead, read the books that inspired them. 

***Dune*** by Frank Herbert (1965)

My friend Patrick and I spent the night outside Escanaba on our way home from an exhausting backpacking trip this summer. Inside the otherwise perfectly pleasant cabin was a VHS copy of David Lynch’s 1984 Dune, which I am confident is the worst movie I have ever seen in my life. It was so bad that my confidence was shaken as I tried to assure Patrick that the book is “actually good.” To test my memory, I reread the book for the first time since high school. Turns out it is good, but probably not for the reasons I remember. I think Paul Atreides might actually be the villain. Let’s see if the 2020 movie is any better.

***Dignity: Seeking Respect in Back Row America*** by Chris Arnade (2019)

Dignity is the kind of book that could be done terribly much more easily than well. Fortunately, Chris Arnade (a working class kid turned banker turned photojournalist) gets into the right places and out of his own way unusually well. The book recounts interviews with people struggling (and usually failing) to get by in the “back row” of America—commonly in places you’ve never heard of. Arnade is a leftist, but the book was published by an at least notionally conservative press. Because Arnade lets people failed by Democrats and Republicans alike speak for themselves, this book is comfortable for no one. The way it has attracted attention from both the left and right gives me some small amount of hope for the post-Trump era, whenever it arrives.

***The Thousand Autumns of Jacob de Zoet*** by David Mitchell (2010)

For centuries, Japan only allowed trade with Europe through a Dutch trading outpost confined to a single small island in the harbor of a provincial port city. This book takes place in the 1790s, following a young Dutch East India Company clerk and his Japanese counterparts. Each side is keenly aware of being on the downslope of their respective empires. Within this uncomfortably relevant historical context, the story follows characters with internal lives recognizable in any age but pressures indiscernible to one another.

***Say Nothing: A True Story of Murder and Memory in Northern Ireland*** by Patrick Radden Keefe (2019)

I haven’t read many books which end with the author naming a living person as the murderer in a high-profile cold case, but that’s exactly what Keefe does in this account of The Troubles. Still, the book doesn’t read like true crime. Instead it feels like a history book (about, among other things, how history gets written). It’s a moving and disconcerting depiction of how in-group solidarity in the face of oppression so easily just recreates the injustice it is resisting.