---
title: Maps of average rainfall in hydrological basins
author: John D. Johnson
date: '2020-05-24'
slug: maps-of-average-rainfall-in-hydrological-basins
categories:
  - United States
tags: []
Description: ''
Tags: []
Categories: []
DisableComments: no
---

A good map has to balance competing objectives. It should be coherent at first glance but still complex enough to reward careful examination. A good map invites the viewer in, often by giving them a personal frame of reference that they can then expand outwards to discover new information. Like all data visualizations, it exists to simply data, but it should do so in a way that informs, rather than misleads.

Often, maps just aren't the right tool for the job. Maps are a terrible way to [communicate election results](https://johndjohnson.info/post/greater-milwaukee-voting-trends/), for instance. The point of an election map should never be to show you who won the election. If that is the goal, just use a table. Election maps are a good way to show who won an election and by how much *in a given location*, but in my experience, insisting that viewers interpret a map in the way you intend it to be interpreted rarely works. The temptation to compare surface areas is just too great. Probably the best solution is just to offer a series of maps, each more accurate along a specific dimension of the truth. That's the idea behind [Ken Field's gallery of 32 different kinds of 2016 election maps](https://carto.maps.arcgis.com/apps/MinimalGallery/index.html?appid=b3d1fe0e8814480993ff5ad8d0c62c32#).